// Dados dos produtos organizados por categoria
const products = {
    nacional: [
        { name: "Palmeiras 25/26", price: "R$ 169,90", img: "fotos/palmeirasverdenova.png" },
        { name: "Palmeiras Branca 25/26", price: "R$ 169,90", img: "fotos/palmeirasbrancanova.png" },
        { name: "Palmeiras Mundial 25", price: "R$ 169,90", img: "fotos/palmeirasmundiaal.png" },
        { name: "Palmeiras away 25", price: "R$ 169,90", img: "fotos/palmeirasaway2025.png" },
        { name: "Palmeiras 24/25", price: "R$ 169,00", img: "fotos/palemirasverde24-25.png" },
        { name: "Nome da Camisa", price: "R$ 169,90", img: "fotos/camisapalmeirasamarela.png" },
        { name: "FLAMENGO LFSTLR 25/26 ADIDAS", price: "R$ 169,90", img: "fotos/CAMISAFLAMENGoLFSTLRADIDAS.jpg" },
        { name: "FLAMENGO 25/26 ADIDAS", price: "R$ 169,90", img: "fotos/FLAMENGO.PNG" },
        { name: "FLAMENGO 25/26 ADIDAS - BRANCA", price: "R$ 169,90", img: "fotos/FLAMENGO 2526 ADIDAS.PNG" },
        { name: "FLAMENGO 25/26 ADIDAS", price: "R$ 169,90", img: "fotos/CAMISAIFLAMENGO2526ADIDAS.jpg" },
        { name: "CORINTHIANS 25/26 NIKE", price: "R$ 169,90", img: "fotos/CORINTHIANS 2526 NIKE.jpg" },
        { name: "CORINTHIANS 25/26 NIKE - PRETA", price: "R$ 169,90", img: "fotos/CORINTHIANS 2526 NIKE - PRETA.jpg" },
        { name: "CORINTHIANS 25/26 NIKE - BRANCA", price: "R$ 169,90", img: "fotos/CORINTHIANS 2526 NIKE - BRANCA.jpg" },
        { name: "CORINTHIANS 24/25 NIKE", price: "R$ 169,90", img: "fotos/CORINTHIANS 2425 NIKE.jpg" },
        { name: "SÃO PAULO 25/26 NEW BALANCE", price: "R$ 169,90", img: "fotos/SÃO PAULO 2526 NEW BALANCE.jpg" },
        { name: "SÃO PAULO 25/26 NEW BALANCE - VERMELHA", price: "R$ 169,90", img: "fotos/SÃO PAULO 25-26 NEW BALANCE - V.jpg" },
        { name: "SANTOS 25/26 UMBRO", price: "R$ 169,90", img: "fotos/SANTOS 2526 UMBRO.jpg" },
        { name: "SANTOS 25/26 UMBRO - BRANCA", price: "R$ 169,90", img: "fotos/SANTOS 2526 UMBRO - - NOVA.jpg" },
        { name: "SANTOS 25/26 UMBRO - AZUL", price: "R$ 169,90", img: "fotos/SANTOS 2526 UMBRO - AZUL.jpg" },
        { name: "CRUZEIRO 25/26 ADIDAS", price: "R$ 169,90", img: "fotos/CRUZEIRO 2526 ADIDAS.jpg" },
    ],
    internacional: [
        { name: "Bohemian Football Club preta", price: "R$ 169,90", img: "fotos/Bohemian Football Club preta.png" },
        { name: "Camiseta Real Madrid Home 24/25", price: "R$ 169,90", img: "fotos/Liverpool 2526 Torcedor Adidas - Preto.jpg" },
        { name: "LIVERPOOL 25/26 ADIDAS", price: "R$ 169,90", img: "fotos/LIVERPOOL 2526 ADIDAS -.jpg" },
        { name: "BARCELONA 24/25 NIKE", price: "R$ 169,90", img: "fotos/BARCELONA 2425 NIKE.jpg" },
        { name: "BARCELONA 25/26 NIKE", price: "R$ 169,90", img: "fotos/BARCELONA 2526 NIKE.jpg" },
        { name: "BARCELONA 25/26 KOBE BRYANT", price: "R$ 169,90", img: "fotos/BARCELONA 2526 KOBE BRYANT.jpg" },
        { name: "PSG 25/26 NIKE - TOTAL 90", price: "R$ 169,90", img: "fotos/PSG-90.jpg" },
        { name: "PSG 25/26 NIKE", price: "R$ 169,90", img: "fotos/PSG 2526 NIKE.jpg" },
        { name: "PSG 25/26 - AZUL", price: "R$ 169,90", img: "fotos/PSG 2526 AZUL.jpg" },
        { name: "REAL MADRID 25/26 ADIDAS", price: "R$ 169,90", img: "fotos/REAL MADRID 2526 ADIDAS.jpg" },
        { name: "REAL MADRID 25/26 ADIDAS - PRETA", price: "R$ 169,90", img: "fotos/REAL MADRID 2526 ADIDAS - PRETA.jpg" },
        { name: "REAL MADRID 23/24 Y-3", price: "R$ 169,90", img: "fotos/REAL MADRID 2324 Y-3.jpg" },
        { name: "REAL MADRID 24/25 ADIDAS", price: "R$ 169,90", img: "fotos/REAL MADRID 2425 ADIDAS.png" },
        { name: "REAL MADRID 23/24 ADIDAS", price: "R$ 169,90", img: "fotos/REAL MADRID 2324 ADIDAS.jpg" }
    ],
    retro: [
        { name: "Brasil 1998 - Amarela", price: "R$ 219,90", img: "fotos/Retro tailandesa Brasil 1998 amarela.jpg" },
        { name: "Brasil 1998 - AZUL", price: "R$ 219,90", img: "fotos/Retro tailandesa Brasil 1998.jpg" },
        { name: "Brasil 2002 - Penta", price: "R$ 219,90", img: "fotos/Retro tailandesa Brasil 2002.jpg" },
        { name: "Brasil 94 - Tetra", price: "R$ 219,90", img: "fotos/Retrô tailandesa brasil 94.jpg" },
        { name: "Retrô França 2006", price: "R$ 219,90", img: "fotos/Retrô tailandesa França 2006.jpg" },
        { name: "Retrô França 98", price: "R$ 219,90", img: "fotos/Retrô tailandesa França 98.jpg" },
        { name: "Retrô Inglaterra", price: "R$ 219,90", img: "fotos/Retrô tailandesa Inglaterra.jpg" },
        { name: "Retrô Argentina 1987", price: "R$ 219,90", img: "fotos/Retrô Argentina 1987.jpg" },
        { name: "Retrô Milan", price: "R$ 219,90", img: "fotos/Retrô Milan listrada.jpg" },
        { name: "Retrô Milan Branca", price: "R$ 219,90", img: "fotos/Retrô Milan branca.png" },
        { name: "Retrô Japão", price: "R$ 219,90", img: "fotos/Retrô Japão.jpg" },
        { name: "Retrô PSG cinza", price: "R$ 219,90", img: "fotos/PSG RETRO.jpg" },
        { name: "Retrô Real Madrid", price: "R$ 219,90", img: "fotos/Retrô Real Madrid.jpg" },
        { name: "Retrô Real Madrid azul", price: "R$ 219,90", img: "fotos/Retrô Real Madrid azul.jpg" },
        { name: "Retrô real Madrid preta", price: "R$ 219,90", img: "fotos/Retrô real Madrid preta.jpg" },
        { name: "Retrô tailandesa Real Madrid 9 Ronaldo", price: "R$ 219,90", img: "fotos/Retrô Real Madrid r9.jpg" },
        { name: "Retrô Manchester united", price: "R$ 219,90", img: "fotos/Retrô Manchester united.jpg" },
        { name: "Retrô Arsenal", price: "R$ 219,90", img: "fotos/Retrô Arsenal.jpg" },
        { name: "Retrô Corinthians kalunga", price: "R$ 219,90", img: "fotos/Retrô Corinthians kalunga.jpg" },
        { name: "Retrô Corinthians listrada", price: "R$ 219,90", img: "fotos/Retrô Corinthians listrada.jpg" },
        { name: "Retrô Corinthians batavo branca", price: "R$ 219,90", img: "fotos/Retrô Corinthians batavo branca.jpg" },
        { name: "Retrô Corinthians suvinil", price: "R$ 219,90", img: "fotos/Retrô Corinthians suvinil.jpg" },
        { name: "Retrô Corinthians vermelha São jorge", price: "R$ 219,90", img: "fotos/Retrô Corinthians vermelha São jorge.jpg" },
        { name: "Retrô Flamengo listrada adriano", price: "R$ 219,90", img: "fotos/Retrô Flamengo.jpg" },
        { name: "Retrô Flamengo azul", price: "R$ 219,90", img: "fotos/Retrô Flamengo azul.jpg" },
        { name: "Retro Barcelona Kluivert 2001/2002", price: "R$ 219,90", img: "fotos/Retro Barcelona Kluivert 2001-2002.jpg" },
        { name: "Retrô Barcelona azul messi", price: "R$ 219,90", img: "fotos/Retrô Barcelona listrada azul messi.jpg" },
        { name: "Retrô santos neymar azul", price: "R$ 219,90", img: "fotos/Retrô santos neymar azul.jpg" },
        { name: "Retrô tailandesa santos neymar branca", price: "R$ 219,90", img: "fotos/Retrô santos neymar branca.jpg" },
        { name: "Retrô tailandesa São Paulo branca motorola", price: "R$ 219,90", img: "fotos/Retrô São Paulo branca motorola.jpg" },
        { name: "Retrô São Paulo listrada motorola", price: "R$ 219,90", img: "fotos/Retrô tailandesa São Paulo listrada motorola.jpg" }
    ],
    jogador: [
        { name: "Camiseta Brasil Amarela – Jogador", price: "R$ 219,90", img: "fotos/PLAYER BRASIL 2526 NIKE.jpg" },
        { name: "CAMISA JOGADOR BRASIL JORDAN 26/27", price: "R$ 219,90", img: "fotos/camisabrasiljogadorazul.jpg" },
        { name: "CAMISA JOGADOR BRASIL 26/27", price: "R$ 219,90", img: "fotos/camisajogadorbrasil26.jpg" },
        { name: "PLAYER BRASIL 25/26 NIKE", price: "R$ 219,90", img: "fotos/CAMISA I PLAYER BRASIL 26-27 NIKE.jpg" },
        { name: "PALMEIRAS 24/25 PUMA - Jogador", price: "R$ 219,90", img: "fotos/PALMEIRAS 2425 PUMA - JOGADOR.jpg" },
        { name: "PALMEIRAS 25/26 PUMA - Jogador", price: "R$ 219,90", img: "fotos/PALMEIRAS 2526 PUMA - JOGADOR.jpg" },
        { name: "PALMEIRAS 25/26 PUMA VERDE - Jogador", price: "R$ 219,90", img: "fotos/PALMEIRAS 2526 PUMA - JOGADOR - V.jpg" },
        { name: "PALMEIRAS 25/26 PUMA - LISTRADA - Jogador", price: "R$ 219,90", img: "fotos/PALMEIRAS 2526 PUMA - LISTRADA - Jogador.jpg" },
        { name: "CORINTHIANS 24/25 NIKE - PRETA COM BRANCO - Jogador", price: "R$ 219,90", img: "fotos/CORINTHIANS 2425 NIKE - BRANCA - JOGADOR.jpg" },
        { name: "CORINTHIANS 25/26 NIKE - BRANCA COM PRETO- Jogador", price: "R$ 219,90", img: "fotos/CORINTHIANS 2526 NIKE - Jogador.jpg" },
        { name: "CORINTHIANS 24/25 NIKE - PRETA - Jogador", price: "R$ 219,90", img: "fotos/CORINTHIANS 2425 NIKE - PRETA - JOGADOR.jpg" },
        { name: "CORINTHIANS 25/26 NIKE - LARANJA - Jogador", price: "R$ 219,90", img: "fotos/CORINTHIANS 2526 NIKE - LARANJA - JOGADOR.jpg" },
        { name: "FLAMENGO 25/26 ADIDAS - JOGADOR", price: "R$ 219,90", img: "fotos/PLAYER FLAMENGO 2526 ADIDAS - JOGADOR.jpg" },
        { name: "FLAMENGO 26/27 ADIDAS - JOGADOR", price: "R$ 219,90", img: "fotos/FLAMENGO 2627 ADIDAS - JOGADOR.jpg" },
        { name: "FLAMENGO 24/25 ADIDAS - JOGADOR", price: "R$ 219,90", img: "fotos/FLAMENGO 2425 ADIDAS - JOGADOR.jpg" },
        { name: "FLAMENGO 25/26 ADIDAS - Jogador", price: "R$ 219,90", img: "fotos/FLAMENGO 2526 ADIDAS - Jogador - v.jpg" },
        { name: "SÃO PAULO 25/26 NEW BALANCE - Jogador", price: "R$ 219,90", img: "fotos/SÃO PAULO 2526 NEW BALANCE - Jogador.jpg" },
        { name: "SÃO PAULO 25/26 NEW BALANCE - Vermelha - Jogador", price: "R$ 219,90", img: "fotos/SÃO PAULO 2526 NEW BALANCE - Vermelha- Jogador.jpg" },
        { name: "SÃO PAULO 25/26 NEW BALANCE - Branca - Jogador", price: "R$ 219,90", img: "fotos/SÃO PAULO 2526 NEW BALANCE - Branca -  Jogador.jpg" },
        { name: "BARCELONA 25/26 KOBE BRYANT - Jogador", price: "R$ 219,90", img: "fotos/BARCELONA 2526 KOBE BRYANT - Jogador.jpg" },
        { name: "Camisa Barcelona x Cactus Jack - Jogador", price: "R$ 219,90", img: "fotos/Camisa Barcelona x Cactus Jack - jogador -.jpg" }
    ],
    infantil: [
        { name: "Kit infantil - Mexico", price: "R$ 169,90", img: "fotos/Kit infantil Mexico.jpg" },
        { name: "Kit infantil Argentina", price: "R$ 169,90", img: "fotos/Kit infantil Argentina.jpg" },
        { name: "Kit infantil Portugal", price: "R$ 169,90", img: "fotos/Kit infantil Portugal.jpg" },
        { name: "Kit infantil Palmeiras Branca", price: "R$ 169,90", img: "fotos/Kit infantil palmeiras branca.jpg" },
        { name: "Kit infantil- Corinthians branca 2025", price: "R$ 169,90", img: "fotos/Kit infantil Corinthians branca 2025.jpg" },
        { name: "Kit infantil- Corinthians preto 2025", price: "R$ 169,90", img: "fotos/Kit infantil Corinthians preto 2025.jpg" },
        { name: "Kit infantil- Flamengo Bege", price: "R$ 169,90", img: "fotos/Kit infantil flamengo bege.jpg" },
        { name: "Kit infantil- Flamengo Branca 2025", price: "R$ 169,90", img: "fotos/Kit infantil Flamengo branca 2025.jpg" },
        { name: "Kit infantil- Santos Branca 2025", price: "R$ 169,90", img: "fotos/Kit infantil santos branca.jpg" },
        { name: "Kit infantil- São Paulo Branca 2025", price: "R$ 169,90", img: "fotos/Kit infantil tailandesa- sao paulo branca 2025.jpg" },
        { name: "Kit infantil- Vasco Preto 2024", price: "R$ 169,90", img: "fotos/Kit infantil vasco preto 2024.jpg" }
    ],
    selecao: [
        { name: "BRASIL 26/27 JORDAN", price: "R$ 169,90", img: "fotos/BRASIL 2627 JORDAN.jpg" },
        { name: "BRASIL 24/25 NIKE", price: "R$ 169,90", img: "fotos/BRASIL 2425 NIKE.jpg" },
        { name: "Brasil guaraná Disponível em mais cores", price: "R$ 169,90", img: "fotos/Brasil guaraná disponível em mais cores.jpg" },
        { name: "Camiseta Itália Home 24/25", price: "R$ 169,90", img: "fotos/ITÁLIA 2425 ADIDAS.jpg" },
        { name: "ITÁLIA 26/27 ADIDAS", price: "R$ 169,90", img: "fotos/ITÁLIA 2627 ADIDAS.jpg" },
        { name: "ITÁLIA 26/27 ADIDAS AZUL", price: "R$ 169,90", img: "fotos/ITÁLIA 2627 ADIDAS AZUL.jpg" },
        { name: "ALEMANHA 26/27 ADIDAS", price: "R$ 169,90", img: "fotos/ALEMANHA 2627 ADIDAS.jpg" },
        { name: "MÉXICO 26/27 ADIDAS", price: "R$ 169,90", img: "fotos/MÉXICO 2627 ADIDAS.jpg" },
        { name: "CROÁCIA 24/25 NIKE", price: "R$ 169,90", img: "fotos/CROÁCIA 2425 NIKE.jpg" },
        { name: "INGLATERRA 24/25 NIKE", price: "R$ 169,90", img: "fotos/INGLATERRA 2425 NIKE.png" },
        { name: "PORTUGAL 26/27 PUMA", price: "R$ 169,90", img: "fotos/PORTUGAL 2627 PUMA--.jpg" },
        { name: "JAPÃO 26/27 ADIDAS", price: "R$ 169,90", img: "fotos/camisa japao.jpeg" },
        { name: "MÉXICO 26/27 ADIDAS", price: "R$ 169,90", img: "fotos/camisamexico26.jpeg" },
    ]
};

// Labels das categorias
const categoryLabels = {
    nacional: { title: "Camisa Nacional", icon: "flag" },
    internacional: { title: "Camisa Internacional", icon: "globe" },
    retro: { title: "Camisa Retrô", icon: "clock" },
    jogador: { title: "Camisa Jogador", icon: "heart" },
    infantil: { title: "Conjunto Infantil", icon: "smile" },
    selecao: { title: "Seleção", icon: "star" }
};

// Banner rotativo
const banners = [
    { img: "fotos/banner-brasilduascamias.jpeg", link: "#selecao" },
    { img: "fotos/banner-brasilamarela.jpeg", link: "#selecao" },
    { img: "fotos/banner-brasilazul.jpeg", link: "#selecao" }
];

